### ISSUE TITLE
cannot use admin,plz help

### ISSUE THREAD

**Issue by tvvocold** [shader/arc-openshift#2]
http://arclanguage.org/item?id=18840

**Comment by shader** [comment]
app-root/repo is the "root" directory of the arc server, so paths are relative to that. The admin file itself is defined as (= adminfile\* (+ srvdir\* "admins")), with srvdir\* defaulting to "www/". Thus it expects admins to be listed as space-separated usernames in the "app-root/repo/www/admins" file. Try adding "admin" to that file and restarting.

Alternatively, change srvdir\* to something other than "www", set the path in adminfile\* directly, or hardcode your admin usernames by setting admins\* itself in main.arc. The admins\* variable should be a list of string usernames, like ("admin" "root" "joe")

Try a full "rhc app force-stop" and "rhc app start" if rhc restart doesn't seem to work.
